# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 626)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.base_frame = QtWidgets.QFrame(self.centralwidget)
        self.base_frame.setStyleSheet("\n"
"QWidget{\n"
"    background-color: rgb(40, 44, 52);\n"
"    color: rgb(189, 147, 249);\n"
"    font: 10pt \"Segoe UI\";\n"
"    border:none;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(33, 37, 43, 180);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {    \n"
"    background-color: transparent;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 58);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(33, 37, 43);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(33, 37, 43);\n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 1px 0 1px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(189, 147, 249);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(189, 147, 249);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(./assets/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(./assets/icons/images/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 121, 198);    \n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"QCommandLinkButton {    \n"
"    color: rgb(255, 121, 198);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QCommandLinkButton:hover {    \n"
"    color: rgb(255, 170, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"}\n"
"QCommandLinkButton:pressed {    \n"
"    color: rgb(189, 147, 249);\n"
"    background-color: rgb(52, 58, 71);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"QPushButton {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"border: 1px solid rgb(189, 147, 249);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border: 2px solid rgb(189, 147, 249);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* * * * * * * * * * * * * CUSTOM BTNS */\n"
"\n"
"\n"
"QPushButton#btn_welcome {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-radius:0px;\n"
"    background-color: rgb(33, 42, 51);\n"
"    text-align: left;\n"
"    padding-left: 25px;\n"
"}\n"
"QPushButton#btn_welcome:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius:0px;\n"
"}\n"
"QPushButton#btn_welcome:pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"#frame_nav .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-radius:0px;\n"
"    /*border-left: 20px solid transparent;*/\n"
"    background-color: rgb(36, 45, 54);\n"
"    text-align: left;\n"
"    padding-left: 27px;\n"
"}\n"
"#frame_nav .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#frame_nav .QPushButton:pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"/* -------------------- */\n"
"\n"
"#frame_btn_cmr .QPushButton {\n"
"    background-color: rgb(33, 37, 43);\n"
"border:none;\n"
"}\n"
"#frame_btn_cmr .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#frame_btn_cmr .QPushButton:pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"\n"
"")
        self.base_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.base_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.base_frame.setObjectName("base_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.base_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_header = QtWidgets.QFrame(self.base_frame)
        self.frame_header.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_header.setObjectName("frame_header")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_header)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_welcome = QtWidgets.QPushButton(self.frame_header)
        self.btn_welcome.setMinimumSize(QtCore.QSize(70, 50))
        self.btn_welcome.setMaximumSize(QtCore.QSize(70, 50))
        self.btn_welcome.setStyleSheet("")
        self.btn_welcome.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./assets/icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_welcome.setIcon(icon)
        self.btn_welcome.setIconSize(QtCore.QSize(24, 24))
        self.btn_welcome.setObjectName("btn_welcome")
        self.gridLayout_3.addWidget(self.btn_welcome, 0, 0, 2, 1)
        self.frame = QtWidgets.QFrame(self.frame_header)
        self.frame.setMinimumSize(QtCore.QSize(0, 24))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_title = QtWidgets.QFrame(self.frame)
        self.frame_title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_title.setObjectName("frame_title")
        self.label_path = QtWidgets.QLabel(self.frame_title)
        self.label_path.setGeometry(QtCore.QRect(0, 4, 171, 20))
        self.label_path.setStyleSheet("font-size:12pt; font-weight:700; color:#bd93f9;\n"
"margin-left:10px;")
        self.label_path.setObjectName("label_path")
        self.horizontalLayout_2.addWidget(self.frame_title)
        self.frame_btn_cmr = QtWidgets.QFrame(self.frame)
        self.frame_btn_cmr.setMinimumSize(QtCore.QSize(72, 24))
        self.frame_btn_cmr.setMaximumSize(QtCore.QSize(72, 24))
        self.frame_btn_cmr.setStyleSheet("border-radius:none;")
        self.frame_btn_cmr.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_btn_cmr.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_btn_cmr.setObjectName("frame_btn_cmr")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_btn_cmr)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btn_cmr)
        self.btn_minimize.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_minimize.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./assets/icons/cil-minus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_minimize.setIcon(icon1)
        self.btn_minimize.setIconSize(QtCore.QSize(24, 24))
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btn_cmr)
        self.btn_maximize.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_maximize.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_maximize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./assets/icons/cil-window-restore.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_maximize.setIcon(icon2)
        self.btn_maximize.setIconSize(QtCore.QSize(24, 24))
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout.addWidget(self.btn_maximize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btn_cmr)
        self.btn_close.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_close.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./assets/icons/cil-x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_close.setIcon(icon3)
        self.btn_close.setIconSize(QtCore.QSize(24, 24))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.horizontalLayout_2.addWidget(self.frame_btn_cmr)
        self.gridLayout_3.addWidget(self.frame, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_header)
        self.frame_3.setStyleSheet("background-color: rgb(51, 61, 73);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(356, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_time = QtWidgets.QLabel(self.frame_3)
        self.label_time.setMinimumSize(QtCore.QSize(171, 31))
        self.label_time.setStyleSheet("font-size:10pt;\n"
"color:#bd93f9;\n"
"")
        self.label_time.setObjectName("label_time")
        self.horizontalLayout_3.addWidget(self.label_time)
        spacerItem1 = QtWidgets.QSpacerItem(355, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_3.addWidget(self.frame_3, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_header, 0, 0, 1, 2)
        self.frame_nav = QtWidgets.QFrame(self.base_frame)
        self.frame_nav.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_nav.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_nav.setStyleSheet("")
        self.frame_nav.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_nav.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_nav.setObjectName("frame_nav")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_nav)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_gestion = QtWidgets.QPushButton(self.frame_nav)
        self.btn_gestion.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_gestion.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./assets/icons/cil-folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_gestion.setIcon(icon4)
        self.btn_gestion.setIconSize(QtCore.QSize(24, 24))
        self.btn_gestion.setObjectName("btn_gestion")
        self.verticalLayout.addWidget(self.btn_gestion)
        self.btn_g_entre = QtWidgets.QPushButton(self.frame_nav)
        self.btn_g_entre.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_g_entre.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./assets/icons/cil-input.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_g_entre.setIcon(icon5)
        self.btn_g_entre.setIconSize(QtCore.QSize(24, 24))
        self.btn_g_entre.setObjectName("btn_g_entre")
        self.verticalLayout.addWidget(self.btn_g_entre)
        self.btn_g_produit = QtWidgets.QPushButton(self.frame_nav)
        self.btn_g_produit.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_g_produit.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./assets/icons/cil-briefcase.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_g_produit.setIcon(icon6)
        self.btn_g_produit.setIconSize(QtCore.QSize(24, 24))
        self.btn_g_produit.setObjectName("btn_g_produit")
        self.verticalLayout.addWidget(self.btn_g_produit)
        self.btn_ventes = QtWidgets.QPushButton(self.frame_nav)
        self.btn_ventes.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_ventes.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./assets/icons/cil-chart-line.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_ventes.setIcon(icon7)
        self.btn_ventes.setObjectName("btn_ventes")
        self.verticalLayout.addWidget(self.btn_ventes)
        spacerItem2 = QtWidgets.QSpacerItem(20, 311, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_settings = QtWidgets.QPushButton(self.frame_nav)
        self.btn_settings.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_settings.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./assets/icons/cil-settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_settings.setIcon(icon8)
        self.btn_settings.setIconSize(QtCore.QSize(24, 24))
        self.btn_settings.setObjectName("btn_settings")
        self.verticalLayout.addWidget(self.btn_settings)
        self.gridLayout_2.addWidget(self.frame_nav, 1, 0, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.base_frame)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_welcome = QtWidgets.QWidget()
        self.page_welcome.setStyleSheet("")
        self.page_welcome.setObjectName("page_welcome")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_welcome)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_26 = QtWidgets.QLabel(self.page_welcome)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_welcome)
        self.page_g_produit = QtWidgets.QWidget()
        self.page_g_produit.setStyleSheet("b")
        self.page_g_produit.setObjectName("page_g_produit")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_g_produit)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.page_g_produit)
        self.tabWidget.setStyleSheet("background: rgb(33, 42, 51);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 2, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 0, 5, 11, 1)
        spacerItem5 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 7, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(144, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 8, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem7, 1, 1, 2, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 1, 4, 2, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 86, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 1, 6, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem10, 1, 8, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setMinimumSize(QtCore.QSize(141, 31))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setMinimumSize(QtCore.QSize(141, 31))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setMinimumSize(QtCore.QSize(141, 31))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setMinimumSize(QtCore.QSize(141, 31))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.horizontalLayout_8.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.linedit_edit_reference = QtWidgets.QLineEdit(self.tab)
        self.linedit_edit_reference.setMinimumSize(QtCore.QSize(221, 35))
        self.linedit_edit_reference.setStyleSheet("")
        self.linedit_edit_reference.setObjectName("linedit_edit_reference")
        self.verticalLayout_7.addWidget(self.linedit_edit_reference)
        self.linedit_edit_des = QtWidgets.QLineEdit(self.tab)
        self.linedit_edit_des.setMinimumSize(QtCore.QSize(221, 35))
        self.linedit_edit_des.setObjectName("linedit_edit_des")
        self.verticalLayout_7.addWidget(self.linedit_edit_des)
        self.linedite_edit_prix = QtWidgets.QLineEdit(self.tab)
        self.linedite_edit_prix.setMinimumSize(QtCore.QSize(221, 35))
        self.linedite_edit_prix.setObjectName("linedite_edit_prix")
        self.verticalLayout_7.addWidget(self.linedite_edit_prix)
        self.btn_edite_p = QtWidgets.QPushButton(self.tab)
        self.btn_edite_p.setMinimumSize(QtCore.QSize(140, 41))
        self.btn_edite_p.setStyleSheet("border: 1px solid #ffaa00;\n"
"    ")
        self.btn_edite_p.setObjectName("btn_edite_p")
        self.verticalLayout_7.addWidget(self.btn_edite_p)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.gridLayout_5.addLayout(self.horizontalLayout_8, 2, 6, 3, 3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setMinimumSize(QtCore.QSize(141, 31))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.btn_create_p_csv = QtWidgets.QPushButton(self.tab)
        self.btn_create_p_csv.setMinimumSize(QtCore.QSize(140, 41))
        self.btn_create_p_csv.setMaximumSize(QtCore.QSize(140, 41))
        self.btn_create_p_csv.setStyleSheet("")
        self.btn_create_p_csv.setObjectName("btn_create_p_csv")
        self.horizontalLayout_12.addWidget(self.btn_create_p_csv)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 3, 0, 1, 5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(6, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setMinimumSize(QtCore.QSize(141, 31))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMinimumSize(QtCore.QSize(141, 31))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setMinimumSize(QtCore.QSize(141, 31))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setMinimumSize(QtCore.QSize(141, 31))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 4, 0, 3, 3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.linedit_reference = QtWidgets.QLineEdit(self.tab)
        self.linedit_reference.setMinimumSize(QtCore.QSize(221, 35))
        self.linedit_reference.setStyleSheet("")
        self.linedit_reference.setObjectName("linedit_reference")
        self.verticalLayout_5.addWidget(self.linedit_reference)
        self.linedit_designation = QtWidgets.QLineEdit(self.tab)
        self.linedit_designation.setMinimumSize(QtCore.QSize(221, 35))
        self.linedit_designation.setObjectName("linedit_designation")
        self.verticalLayout_5.addWidget(self.linedit_designation)
        self.linedit_prix = QtWidgets.QLineEdit(self.tab)
        self.linedit_prix.setMinimumSize(QtCore.QSize(221, 35))
        self.linedit_prix.setObjectName("linedit_prix")
        self.verticalLayout_5.addWidget(self.linedit_prix)
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setMinimumSize(QtCore.QSize(141, 31))
        self.label_27.setObjectName("label_27")
        self.verticalLayout_5.addWidget(self.label_27)
        self.btn_create_p = QtWidgets.QPushButton(self.tab)
        self.btn_create_p.setMinimumSize(QtCore.QSize(140, 41))
        self.btn_create_p.setStyleSheet("")
        self.btn_create_p.setObjectName("btn_create_p")
        self.verticalLayout_5.addWidget(self.btn_create_p)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 4, 3, 5, 2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 82, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem11, 5, 7, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line_3.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_5.addWidget(self.line_3, 6, 6, 1, 3)
        spacerItem12 = QtWidgets.QSpacerItem(152, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem12, 7, 6, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 7, 7, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(151, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem13, 7, 8, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 179, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem14, 8, 0, 3, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 79, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem15, 8, 7, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 126, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem16, 9, 3, 2, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setMinimumSize(QtCore.QSize(189, 31))
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_5.addWidget(self.label_28)
        self.linedit_delete_p = QtWidgets.QLineEdit(self.tab)
        self.linedit_delete_p.setMinimumSize(QtCore.QSize(221, 35))
        self.linedit_delete_p.setStyleSheet("")
        self.linedit_delete_p.setObjectName("linedit_delete_p")
        self.horizontalLayout_5.addWidget(self.linedit_delete_p)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem17 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        self.btn_delete_p = QtWidgets.QPushButton(self.tab)
        self.btn_delete_p.setMinimumSize(QtCore.QSize(222, 35))
        self.btn_delete_p.setMaximumSize(QtCore.QSize(221, 35))
        self.btn_delete_p.setStyleSheet("border: 1px solid rgb(255, 21, 0);\n"
"")
        self.btn_delete_p.setObjectName("btn_delete_p")
        self.horizontalLayout_9.addWidget(self.btn_delete_p)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.gridLayout_5.addLayout(self.verticalLayout_11, 9, 6, 1, 3)
        spacerItem18 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem18, 10, 7, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 5, 1, 2)
        spacerItem19 = QtWidgets.QSpacerItem(240, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem19, 1, 6, 1, 2)
        spacerItem20 = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem20, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setMinimumSize(QtCore.QSize(141, 31))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        self.linedit_search_produit = QtWidgets.QLineEdit(self.tab_2)
        self.linedit_search_produit.setMinimumSize(QtCore.QSize(50, 35))
        self.linedit_search_produit.setStyleSheet("")
        self.linedit_search_produit.setObjectName("linedit_search_produit")
        self.horizontalLayout_4.addWidget(self.linedit_search_produit)
        self.btn_search_produit = QtWidgets.QPushButton(self.tab_2)
        self.btn_search_produit.setMinimumSize(QtCore.QSize(91, 35))
        self.btn_search_produit.setStyleSheet("")
        self.btn_search_produit.setObjectName("btn_search_produit")
        self.horizontalLayout_4.addWidget(self.btn_search_produit)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 1, 0, 1, 3)
        spacerItem21 = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem21, 0, 2, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 1, 1, 1)
        self.table_rupture_stock = QtWidgets.QTableWidget(self.tab_2)
        self.table_rupture_stock.setStyleSheet("")
        self.table_rupture_stock.setObjectName("table_rupture_stock")
        self.table_rupture_stock.setColumnCount(4)
        self.table_rupture_stock.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_rupture_stock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_rupture_stock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_rupture_stock.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_rupture_stock.setHorizontalHeaderItem(3, item)
        self.gridLayout_7.addWidget(self.table_rupture_stock, 2, 0, 1, 8)
        spacerItem22 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem22, 1, 3, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem23, 0, 7, 1, 1)
        self.btn_refrech_table_rupture_stock = QtWidgets.QPushButton(self.tab_2)
        self.btn_refrech_table_rupture_stock.setMinimumSize(QtCore.QSize(91, 35))
        self.btn_refrech_table_rupture_stock.setStyleSheet("")
        self.btn_refrech_table_rupture_stock.setObjectName("btn_refrech_table_rupture_stock")
        self.gridLayout_7.addWidget(self.btn_refrech_table_rupture_stock, 1, 4, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_g_produit)
        self.page_g_entre_p = QtWidgets.QWidget()
        self.page_g_entre_p.setObjectName("page_g_entre_p")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_g_entre_p)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem24 = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_11.addItem(spacerItem24, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_g_entre_p)
        self.label_3.setMaximumSize(QtCore.QSize(501, 31))
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_11.addItem(spacerItem25, 0, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.page_g_entre_p)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem26 = QtWidgets.QSpacerItem(20, 142, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_10.addItem(spacerItem26, 0, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(227, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_10.addItem(spacerItem27, 1, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(227, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_10.addItem(spacerItem28, 1, 3, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem29 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem29)
        self.btn_create_entre = QtWidgets.QPushButton(self.frame_4)
        self.btn_create_entre.setMinimumSize(QtCore.QSize(237, 35))
        self.btn_create_entre.setMaximumSize(QtCore.QSize(221, 35))
        self.btn_create_entre.setStyleSheet("")
        self.btn_create_entre.setObjectName("btn_create_entre")
        self.horizontalLayout_14.addWidget(self.btn_create_entre)
        self.gridLayout_10.addLayout(self.horizontalLayout_14, 2, 1, 1, 2)
        spacerItem30 = QtWidgets.QSpacerItem(20, 141, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_10.addItem(spacerItem30, 3, 2, 1, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_45 = QtWidgets.QLabel(self.frame_4)
        self.label_45.setMinimumSize(QtCore.QSize(141, 31))
        self.label_45.setMaximumSize(QtCore.QSize(141, 40))
        self.label_45.setObjectName("label_45")
        self.verticalLayout_18.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.frame_4)
        self.label_46.setMinimumSize(QtCore.QSize(141, 31))
        self.label_46.setMaximumSize(QtCore.QSize(141, 41))
        self.label_46.setObjectName("label_46")
        self.verticalLayout_18.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.frame_4)
        self.label_47.setMinimumSize(QtCore.QSize(141, 31))
        self.label_47.setMaximumSize(QtCore.QSize(141, 40))
        self.label_47.setObjectName("label_47")
        self.verticalLayout_18.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.frame_4)
        self.label_48.setMinimumSize(QtCore.QSize(141, 31))
        self.label_48.setMaximumSize(QtCore.QSize(141, 40))
        self.label_48.setObjectName("label_48")
        self.verticalLayout_18.addWidget(self.label_48)
        self.gridLayout_10.addLayout(self.verticalLayout_18, 1, 1, 1, 1)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_49 = QtWidgets.QLabel(self.frame_4)
        self.label_49.setMinimumSize(QtCore.QSize(141, 31))
        self.label_49.setObjectName("label_49")
        self.verticalLayout_19.addWidget(self.label_49)
        self.linedit_reference_entre = QtWidgets.QLineEdit(self.frame_4)
        self.linedit_reference_entre.setMinimumSize(QtCore.QSize(221, 35))
        self.linedit_reference_entre.setStyleSheet("")
        self.linedit_reference_entre.setObjectName("linedit_reference_entre")
        self.verticalLayout_19.addWidget(self.linedit_reference_entre)
        self.linedit_quantite_entre = QtWidgets.QLineEdit(self.frame_4)
        self.linedit_quantite_entre.setMinimumSize(QtCore.QSize(221, 35))
        self.linedit_quantite_entre.setStyleSheet("")
        self.linedit_quantite_entre.setText("")
        self.linedit_quantite_entre.setObjectName("linedit_quantite_entre")
        self.verticalLayout_19.addWidget(self.linedit_quantite_entre)
        self.linedit_raison_entre = QtWidgets.QLineEdit(self.frame_4)
        self.linedit_raison_entre.setMinimumSize(QtCore.QSize(221, 35))
        self.linedit_raison_entre.setStyleSheet("")
        self.linedit_raison_entre.setObjectName("linedit_raison_entre")
        self.verticalLayout_19.addWidget(self.linedit_raison_entre)
        self.gridLayout_10.addLayout(self.verticalLayout_19, 1, 2, 1, 1)
        self.gridLayout_11.addWidget(self.frame_4, 1, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_g_entre_p)
        self.page_ventes_p = QtWidgets.QWidget()
        self.page_ventes_p.setObjectName("page_ventes_p")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_ventes_p)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem31 = QtWidgets.QSpacerItem(323, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_13.addItem(spacerItem31, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_ventes_p)
        self.label_4.setMaximumSize(QtCore.QSize(501, 31))
        self.label_4.setObjectName("label_4")
        self.gridLayout_13.addWidget(self.label_4, 0, 1, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(322, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_13.addItem(spacerItem32, 0, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.page_ventes_p)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem33 = QtWidgets.QSpacerItem(20, 166, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_12.addItem(spacerItem33, 0, 2, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(227, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_12.addItem(spacerItem34, 1, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_50 = QtWidgets.QLabel(self.frame_5)
        self.label_50.setMinimumSize(QtCore.QSize(141, 31))
        self.label_50.setMaximumSize(QtCore.QSize(141, 40))
        self.label_50.setObjectName("label_50")
        self.verticalLayout_10.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.frame_5)
        self.label_51.setMinimumSize(QtCore.QSize(141, 31))
        self.label_51.setMaximumSize(QtCore.QSize(141, 40))
        self.label_51.setObjectName("label_51")
        self.verticalLayout_10.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.frame_5)
        self.label_52.setMinimumSize(QtCore.QSize(141, 31))
        self.label_52.setMaximumSize(QtCore.QSize(141, 41))
        self.label_52.setObjectName("label_52")
        self.verticalLayout_10.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.frame_5)
        self.label_53.setMinimumSize(QtCore.QSize(141, 31))
        self.label_53.setMaximumSize(QtCore.QSize(141, 41))
        self.label_53.setObjectName("label_53")
        self.verticalLayout_10.addWidget(self.label_53)
        self.gridLayout_12.addLayout(self.verticalLayout_10, 1, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_54 = QtWidgets.QLabel(self.frame_5)
        self.label_54.setMinimumSize(QtCore.QSize(141, 31))
        self.label_54.setMaximumSize(QtCore.QSize(141, 40))
        self.label_54.setObjectName("label_54")
        self.verticalLayout_9.addWidget(self.label_54)
        self.linedit_reference_ventes = QtWidgets.QLineEdit(self.frame_5)
        self.linedit_reference_ventes.setMinimumSize(QtCore.QSize(221, 35))
        self.linedit_reference_ventes.setStyleSheet("")
        self.linedit_reference_ventes.setObjectName("linedit_reference_ventes")
        self.verticalLayout_9.addWidget(self.linedit_reference_ventes)
        self.linedit_quantite_ventes = QtWidgets.QLineEdit(self.frame_5)
        self.linedit_quantite_ventes.setMinimumSize(QtCore.QSize(221, 35))
        self.linedit_quantite_ventes.setStyleSheet("")
        self.linedit_quantite_ventes.setObjectName("linedit_quantite_ventes")
        self.verticalLayout_9.addWidget(self.linedit_quantite_ventes)
        self.btn_vente = QtWidgets.QPushButton(self.frame_5)
        self.btn_vente.setMinimumSize(QtCore.QSize(242, 35))
        self.btn_vente.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_vente.setStyleSheet("")
        self.btn_vente.setObjectName("btn_vente")
        self.verticalLayout_9.addWidget(self.btn_vente)
        self.gridLayout_12.addLayout(self.verticalLayout_9, 1, 2, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(227, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_12.addItem(spacerItem35, 1, 3, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 166, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_12.addItem(spacerItem36, 2, 2, 1, 1)
        self.gridLayout_13.addWidget(self.frame_5, 1, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_ventes_p)
        self.page_etat_ventes = QtWidgets.QWidget()
        self.page_etat_ventes.setObjectName("page_etat_ventes")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_etat_ventes)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem37 = QtWidgets.QSpacerItem(414, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_14.addItem(spacerItem37, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_etat_ventes)
        self.label_18.setMaximumSize(QtCore.QSize(501, 31))
        self.label_18.setObjectName("label_18")
        self.gridLayout_14.addWidget(self.label_18, 0, 1, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(287, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_14.addItem(spacerItem38, 0, 2, 1, 2)
        self.table_ventes = QtWidgets.QTableWidget(self.page_etat_ventes)
        self.table_ventes.setMinimumSize(QtCore.QSize(852, 461))
        self.table_ventes.setStyleSheet("")
        self.table_ventes.setObjectName("table_ventes")
        self.table_ventes.setColumnCount(3)
        self.table_ventes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_ventes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ventes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ventes.setHorizontalHeaderItem(2, item)
        self.gridLayout_14.addWidget(self.table_ventes, 1, 0, 1, 4)
        spacerItem39 = QtWidgets.QSpacerItem(681, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_14.addItem(spacerItem39, 2, 0, 1, 3)
        self.btn_refrech_ventes = QtWidgets.QPushButton(self.page_etat_ventes)
        self.btn_refrech_ventes.setMinimumSize(QtCore.QSize(228, 35))
        self.btn_refrech_ventes.setMaximumSize(QtCore.QSize(221, 35))
        self.btn_refrech_ventes.setStyleSheet("")
        self.btn_refrech_ventes.setObjectName("btn_refrech_ventes")
        self.gridLayout_14.addWidget(self.btn_refrech_ventes, 2, 3, 1, 1)
        self.stackedWidget.addWidget(self.page_etat_ventes)
        self.gridLayout_6.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 1, 1, 1)
        self.frame_footer = QtWidgets.QFrame(self.base_frame)
        self.frame_footer.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_footer.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_footer.setStyleSheet("QFrame#frame_footer {\n"
"    background-color: rgb(51, 61, 73);\n"
"    border:none;\n"
"    border-radius: 16px;\n"
"\n"
"\n"
"}")
        self.frame_footer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_footer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_footer.setObjectName("frame_footer")
        self.label_2 = QtWidgets.QLabel(self.frame_footer)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 130, 21))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.frame_footer, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.base_frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_path.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#bd93f9;\"> [*] Epecerie Manager</span></p></body></html>"))
        self.label_time.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:700; color:#bd93f9;\">TextLabel</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#a8b1b8;\">Bienvenue à</span></p><p align=\"center\"><span style=\" font-size:20pt; font-weight:700; color:#bd93f9;\">Epecerie Manager</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Créer &amp; Modifier un produit</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Editer un produit</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Reference</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Designation</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Prix</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Quantite</span></p></body></html>"))
        self.btn_edite_p.setText(_translate("MainWindow", "Edite"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">FILE : </span><span style=\" font-weight:700; font-style:italic; text-decoration: underline;\">NONE</span></p></body></html>"))
        self.btn_create_p_csv.setText(_translate("MainWindow", "load CSV"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Reference</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Designation</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Prix</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Quantite</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">0 default</span></p></body></html>"))
        self.btn_create_p.setText(_translate("MainWindow", "Create"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Editer un produit</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Reference</span></p></body></html>"))
        self.btn_delete_p.setText(_translate("MainWindow", "Suprimer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Cree Del Edit"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Afficher les produit en rupture de stock</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Search by Reference</span></p></body></html>"))
        self.btn_search_produit.setText(_translate("MainWindow", "Search"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Rechercher Un Produit</span></p></body></html>"))
        item = self.table_rupture_stock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ReferencePro"))
        item = self.table_rupture_stock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DesignationPro"))
        item = self.table_rupture_stock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PrixPro"))
        item = self.table_rupture_stock.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "QuantiteStock"))
        self.btn_refrech_table_rupture_stock.setText(_translate("MainWindow", "Refrech"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Search rupture"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:700;\">La gestion des entrées</span></p></body></html>"))
        self.btn_create_entre.setText(_translate("MainWindow", "Create"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Date d\'Entree</span></p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Reference</span></p></body></html>"))
        self.label_47.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Quantite</span></p></body></html>"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:700;\">RaisonSociale</span></p><p><span style=\" font-size:8pt; font-weight:700;\">Fournisseur</span></p></body></html>"))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">datetime.now()</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:700;\">La gestion des Ventes</span></p></body></html>"))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Date Vente</span></p></body></html>"))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Reférence</span></p></body></html>"))
        self.label_52.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Quantite</span></p></body></html>"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">datetime.now()</span></p></body></html>"))
        self.btn_vente.setText(_translate("MainWindow", "Sell"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:700;\">L\'état des ventes</span></p></body></html>"))
        item = self.table_ventes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DateVente"))
        item = self.table_ventes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "produit"))
        item = self.table_ventes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DateVente"))
        self.btn_refrech_ventes.setText(_translate("MainWindow", "refrech"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; color:#bd93f9;\">By : @0xtz - v : 0.0.1</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
